apiVersion: v1
kind: ConfigMap
metadata:
  name: talentloq-config
  namespace: talentloq
data:
  APP_ENV: "production"
  PORT: "8000"
  MONGODB_URL: "mongodb://mongodb-service.talentloq.svc.cluster.local:27017"
  DATABASE_NAME: "talentloq_db"
  ALLOWED_ORIGINS: "http://talentloq.local,http://localhost"
  JWT_ALGORITHM: "HS256"
