apiVersion: v1
kind: Secret
metadata:
  name: talentloq-secret
  namespace: talentloq
type: Opaque
stringData:
  JWT_SECRET: "talentloq_jwt_secret_key_production_32bytes"
  ENCRYPTION_KEY: "dGFsZW50bG9xX2Flc19lbmNyeXB0aW9uX2tleV8zMg=="
  GROQ_API_KEY: ""
  GEMINI_API_KEY: ""
